// Export an assembled lesson as a standalone HTML file.
//
// The classic exporter pulled KaTeX from a CDN, which leaves the file broken
// offline — the one property this app is built around. This one ships the maths
// as written and styles it so it still reads well as plain text.

import type { LessonBuild, LessonScene } from "./lessonApi";

const esc = (s: string) =>
  (s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");

const TYPE_ICON: Record<string, string> = { explain: "📖", example: "🧮", quiz: "❓" };

/** Minimal markdown → HTML: paragraphs, bold, italics and inline code. */
function block(md: string): string {
  return (md || "")
    .split(/\n{2,}/)
    .map((para) => {
      const html = esc(para.trim())
        .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
        .replace(/(^|[^*])\*([^*]+)\*/g, "$1<em>$2</em>")
        .replace(/`([^`]+)`/g, "<code>$1</code>")
        .replace(/\n/g, "<br/>");
      return html ? `<p>${html}</p>` : "";
    })
    .join("\n");
}

function sceneHtml(scene: LessonScene | null, title: string, type: string): string {
  let out = `<section><h2>${TYPE_ICON[type] || ""} ${esc(title)}</h2>`;
  if (!scene) {
    out += "<p><em>(scene not generated)</em></p></section>";
    return out;
  }
  if (scene.type === "quiz") {
    out += `<p><strong>${esc(scene.question || "")}</strong></p><ol type="A">`;
    (scene.choices || []).forEach((c, i) => {
      out += `<li>${esc(c)}${i === (scene.correct_index ?? 0) ? " ✅" : ""}</li>`;
    });
    out += `</ol><p><em>${esc(scene.explanation || "")}</em></p>`;
  } else {
    out += block(scene.narration || "");
    if (scene.classmate_question) {
      out +=
        `<blockquote><strong>🧑‍🎓 Maya asks:</strong> ${esc(scene.classmate_question)}<br/>` +
        `<strong>Answer:</strong> ${esc(scene.classmate_answer || "")}</blockquote>`;
    }
  }
  return out + "</section>";
}

export function exportLesson(
  lesson: LessonBuild,
  scenes: (LessonScene | null)[],
  qa: { role: string; content: string }[] = []
): void {
  let body = lesson.sections
    .map((s, i) => sceneHtml(scenes[i] ?? null, s.title, s.type))
    .join("\n");

  if (qa.length) {
    body += `<section><h2>💬 Questions asked during this lesson</h2>`;
    for (const m of qa) {
      body +=
        m.role === "user"
          ? `<p><strong>Q:</strong> ${esc(m.content)}</p>`
          : `<blockquote>${block(m.content)}</blockquote>`;
    }
    body += "</section>";
  }

  const doc = `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(lesson.title)}</title>
<style>
  body { font-family: Georgia, "Times New Roman", serif; max-width: 760px;
         margin: 40px auto; padding: 0 20px; color: #1c1917; line-height: 1.65; }
  h1 { border-bottom: 2px solid #1c1917; padding-bottom: 8px; }
  h2 { font-size: 1.15rem; margin-top: 0; }
  section { margin: 28px 0; }
  blockquote { background: #f5f5f4; border-left: 3px solid #a8a29e;
               padding: 10px 14px; border-radius: 4px; margin: 14px 0; }
  code { font-family: ui-monospace, "SF Mono", monospace; background: #f5f5f4;
         padding: 1px 4px; border-radius: 3px; }
  footer { margin-top: 40px; font-size: 12px; color: #78716c;
           border-top: 1px solid #e7e5e4; padding-top: 10px; }
</style></head><body>
<h1>${esc(lesson.title)}</h1>
<p><em>Level: ${esc(lesson.level)} · generated by Euclid&rsquo;s Window with a local model</em></p>
${body}
<footer>Exported from Euclid&rsquo;s Window — learn math from first principles.</footer>
</body></html>`;

  const url = URL.createObjectURL(new Blob([doc], { type: "text/html" }));
  const a = document.createElement("a");
  a.href = url;
  a.download = `${lesson.title.replace(/[^a-z0-9]+/gi, "-").toLowerCase() || "lesson"}.html`;
  a.click();
  // Revoke on the next tick so the download has definitely started.
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
